{{- if .Values.app.env.OXR_API_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: currency-converter-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name | default "currency-converter" }}
type: Opaque
stringData:
  OXR_API_KEY: {{ .Values.app.env.OXR_API_KEY | quote }}
{{- end }}
