apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "currency-converter" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name | default "currency-converter" }}
spec:
  selector:
    app: {{ .Values.service.name | default "currency-converter" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
